require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe TipotelefonesController do

  # This should return the minimal set of attributes required to create a valid
  # Tipotelefone. As you add validations to Tipotelefone, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # TipotelefonesController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all tipotelefones as @tipotelefones" do
      tipotelefone = Tipotelefone.create! valid_attributes
      get :index, {}, valid_session
      assigns(:tipotelefones).should eq([tipotelefone])
    end
  end

  describe "GET show" do
    it "assigns the requested tipotelefone as @tipotelefone" do
      tipotelefone = Tipotelefone.create! valid_attributes
      get :show, {:id => tipotelefone.to_param}, valid_session
      assigns(:tipotelefone).should eq(tipotelefone)
    end
  end

  describe "GET new" do
    it "assigns a new tipotelefone as @tipotelefone" do
      get :new, {}, valid_session
      assigns(:tipotelefone).should be_a_new(Tipotelefone)
    end
  end

  describe "GET edit" do
    it "assigns the requested tipotelefone as @tipotelefone" do
      tipotelefone = Tipotelefone.create! valid_attributes
      get :edit, {:id => tipotelefone.to_param}, valid_session
      assigns(:tipotelefone).should eq(tipotelefone)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Tipotelefone" do
        expect {
          post :create, {:tipotelefone => valid_attributes}, valid_session
        }.to change(Tipotelefone, :count).by(1)
      end

      it "assigns a newly created tipotelefone as @tipotelefone" do
        post :create, {:tipotelefone => valid_attributes}, valid_session
        assigns(:tipotelefone).should be_a(Tipotelefone)
        assigns(:tipotelefone).should be_persisted
      end

      it "redirects to the created tipotelefone" do
        post :create, {:tipotelefone => valid_attributes}, valid_session
        response.should redirect_to(Tipotelefone.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved tipotelefone as @tipotelefone" do
        # Trigger the behavior that occurs when invalid params are submitted
        Tipotelefone.any_instance.stub(:save).and_return(false)
        post :create, {:tipotelefone => {}}, valid_session
        assigns(:tipotelefone).should be_a_new(Tipotelefone)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Tipotelefone.any_instance.stub(:save).and_return(false)
        post :create, {:tipotelefone => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested tipotelefone" do
        tipotelefone = Tipotelefone.create! valid_attributes
        # Assuming there are no other tipotelefones in the database, this
        # specifies that the Tipotelefone created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Tipotelefone.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => tipotelefone.to_param, :tipotelefone => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested tipotelefone as @tipotelefone" do
        tipotelefone = Tipotelefone.create! valid_attributes
        put :update, {:id => tipotelefone.to_param, :tipotelefone => valid_attributes}, valid_session
        assigns(:tipotelefone).should eq(tipotelefone)
      end

      it "redirects to the tipotelefone" do
        tipotelefone = Tipotelefone.create! valid_attributes
        put :update, {:id => tipotelefone.to_param, :tipotelefone => valid_attributes}, valid_session
        response.should redirect_to(tipotelefone)
      end
    end

    describe "with invalid params" do
      it "assigns the tipotelefone as @tipotelefone" do
        tipotelefone = Tipotelefone.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Tipotelefone.any_instance.stub(:save).and_return(false)
        put :update, {:id => tipotelefone.to_param, :tipotelefone => {}}, valid_session
        assigns(:tipotelefone).should eq(tipotelefone)
      end

      it "re-renders the 'edit' template" do
        tipotelefone = Tipotelefone.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Tipotelefone.any_instance.stub(:save).and_return(false)
        put :update, {:id => tipotelefone.to_param, :tipotelefone => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested tipotelefone" do
      tipotelefone = Tipotelefone.create! valid_attributes
      expect {
        delete :destroy, {:id => tipotelefone.to_param}, valid_session
      }.to change(Tipotelefone, :count).by(-1)
    end

    it "redirects to the tipotelefones list" do
      tipotelefone = Tipotelefone.create! valid_attributes
      delete :destroy, {:id => tipotelefone.to_param}, valid_session
      response.should redirect_to(tipotelefones_url)
    end
  end

end
