require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe TurmisController do

  # This should return the minimal set of attributes required to create a valid
  # Turmi. As you add validations to Turmi, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # TurmisController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all turmis as @turmis" do
      turmi = Turmi.create! valid_attributes
      get :index, {}, valid_session
      assigns(:turmis).should eq([turmi])
    end
  end

  describe "GET show" do
    it "assigns the requested turmi as @turmi" do
      turmi = Turmi.create! valid_attributes
      get :show, {:id => turmi.to_param}, valid_session
      assigns(:turmi).should eq(turmi)
    end
  end

  describe "GET new" do
    it "assigns a new turmi as @turmi" do
      get :new, {}, valid_session
      assigns(:turmi).should be_a_new(Turmi)
    end
  end

  describe "GET edit" do
    it "assigns the requested turmi as @turmi" do
      turmi = Turmi.create! valid_attributes
      get :edit, {:id => turmi.to_param}, valid_session
      assigns(:turmi).should eq(turmi)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Turmi" do
        expect {
          post :create, {:turmi => valid_attributes}, valid_session
        }.to change(Turmi, :count).by(1)
      end

      it "assigns a newly created turmi as @turmi" do
        post :create, {:turmi => valid_attributes}, valid_session
        assigns(:turmi).should be_a(Turmi)
        assigns(:turmi).should be_persisted
      end

      it "redirects to the created turmi" do
        post :create, {:turmi => valid_attributes}, valid_session
        response.should redirect_to(Turmi.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved turmi as @turmi" do
        # Trigger the behavior that occurs when invalid params are submitted
        Turmi.any_instance.stub(:save).and_return(false)
        post :create, {:turmi => {}}, valid_session
        assigns(:turmi).should be_a_new(Turmi)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Turmi.any_instance.stub(:save).and_return(false)
        post :create, {:turmi => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested turmi" do
        turmi = Turmi.create! valid_attributes
        # Assuming there are no other turmis in the database, this
        # specifies that the Turmi created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Turmi.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => turmi.to_param, :turmi => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested turmi as @turmi" do
        turmi = Turmi.create! valid_attributes
        put :update, {:id => turmi.to_param, :turmi => valid_attributes}, valid_session
        assigns(:turmi).should eq(turmi)
      end

      it "redirects to the turmi" do
        turmi = Turmi.create! valid_attributes
        put :update, {:id => turmi.to_param, :turmi => valid_attributes}, valid_session
        response.should redirect_to(turmi)
      end
    end

    describe "with invalid params" do
      it "assigns the turmi as @turmi" do
        turmi = Turmi.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Turmi.any_instance.stub(:save).and_return(false)
        put :update, {:id => turmi.to_param, :turmi => {}}, valid_session
        assigns(:turmi).should eq(turmi)
      end

      it "re-renders the 'edit' template" do
        turmi = Turmi.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Turmi.any_instance.stub(:save).and_return(false)
        put :update, {:id => turmi.to_param, :turmi => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested turmi" do
      turmi = Turmi.create! valid_attributes
      expect {
        delete :destroy, {:id => turmi.to_param}, valid_session
      }.to change(Turmi, :count).by(-1)
    end

    it "redirects to the turmis list" do
      turmi = Turmi.create! valid_attributes
      delete :destroy, {:id => turmi.to_param}, valid_session
      response.should redirect_to(turmis_url)
    end
  end

end
